# Generated by Django 5.2.10 on 2026-06-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_usermodel_is_admin_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.categorymodel'),
        ),
    ]
