# Generated by Django 5.2.10 on 2026-07-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizemodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariantmodel',
            name='size',
        ),
        migrations.RemoveIndex(
            model_name='productvariantmodel',
            name='shop_produc_product_eba4d8_idx',
        ),
        migrations.RemoveField(
            model_name='productvariantmodel',
            name='color',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='attribute_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='variant_attribute_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='productvariantmodel',
            index=models.Index(fields=['product'], name='shop_produc_product_de0650_idx'),
        ),
        migrations.DeleteModel(
            name='SizeModel',
        ),
    ]
