# Generated by Django 5.2.10 on 2026-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_sizemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
