# Generated by Django 5.2.10 on 2026-07-24 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_ordermodel_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StockReservationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='reserved', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='shop.orderitemmodel')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productvariantmodel')),
            ],
        ),
    ]
